main: ${mainClass}
name: ${name}
version: ${version}
api-version: 1.13
author: royalkingkb
softdepend: [stevecinema-economy, mcatlas-economy]
depend: [Vault]
commands:
  coinflip:
    description: Coinflip someone
    aliases: [coin]
  coinflipaccept:
    description: Accept a coinflip
    aliases: [coinaccept]
  roll:
    description: 1 in 10 chance of 10x your money
